export const GET_DESTINATIONS_DATA = "GET_DESTINATIONS_DATA";

export const GET_TECH_DATA = "GET_TECH_DATA";

export const GET_CREW_DATA = "GET_CREW_DATA";

export const CHANGE_ACTIVE_LINK = "CHANGE_ACTIVE_LINK";

export const CHANGE_BACKGROUND = "CHANGE_BACKGROUND";
